package commands

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

func TestJSONNotificationConfigStore(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "notification_config.json")
	store := NewJSONNotificationConfigStore(filePath)

	if err := store.SetChannel(context.Background(), "guild-1", "channel-1"); err != nil {
		t.Fatalf("expected nil error, got %v", err)
	}

	if err := store.SetRole(context.Background(), "guild-1", "role-1"); err != nil {
		t.Fatalf("expected nil error, got %v", err)
	}

	byMinutesID, err := store.AddByMinutesNotification(context.Background(), "guild-1", ByMinutesNotificationInput{
		EveryMinutes: 240,
		BaseHour:     "16:00",
		Title:        "Recordatorio",
		Message:      "Enviar reporte",
	})
	if err != nil {
		t.Fatalf("expected nil error creating byminutes notification, got %v", err)
	}

	if byMinutesID == "" {
		t.Fatal("expected generated byminutes notification id")
	}

	dailyID, err := store.AddDailyNotification(context.Background(), "guild-1", DailyNotificationInput{
		BaseHour: "18:30",
		Title:    "Diario",
		Message:  "Revisión diaria",
	})
	if err != nil {
		t.Fatalf("expected nil error creating daily notification, got %v", err)
	}

	if dailyID == "" {
		t.Fatal("expected generated daily notification id")
	}

	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("expected config file to exist, got %v", err)
	}

	var state notificationConfigState
	if err := json.Unmarshal(content, &state); err != nil {
		t.Fatalf("expected valid json, got %v", err)
	}

	guildConfig := state.Guilds["guild-1"]
	if guildConfig.ChannelID != "channel-1" {
		t.Fatalf("expected channel-1, got %q", guildConfig.ChannelID)
	}

	if guildConfig.RoleID != "role-1" {
		t.Fatalf("expected role-1, got %q", guildConfig.RoleID)
	}

	notificationFilePath := filepath.Join(filepath.Dir(filePath), "notifications.json")
	notificationContent, err := os.ReadFile(notificationFilePath)
	if err != nil {
		t.Fatalf("expected notifications file to exist, got %v", err)
	}

	var notificationState notificationScheduleState
	if err := json.Unmarshal(notificationContent, &notificationState); err != nil {
		t.Fatalf("expected valid notifications json, got %v", err)
	}

	if len(guildConfig.ByMinutesNotifications) != 1 {
		t.Fatalf("expected 1 byminutes config entry, got %d", len(guildConfig.ByMinutesNotifications))
	}

	if len(guildConfig.DailyNotifications) != 1 {
		t.Fatalf("expected 1 daily config entry, got %d", len(guildConfig.DailyNotifications))
	}

	notification := guildConfig.ByMinutesNotifications[0]
	if notification.ID == "" || notification.EveryMinutes != 240 || notification.BaseHour != "16:00" || notification.Title != "Recordatorio" || notification.Message != "Enviar reporte" {
		t.Fatalf("unexpected byminutes notification: %+v", notification)
	}

	if len(notificationState.Notifications) != 2 {
		t.Fatalf("expected 2 scheduled notifications, got %d", len(notificationState.Notifications))
	}

	foundByMinutes := false
	foundDaily := false
	for _, scheduled := range notificationState.Notifications {
		if scheduled.ID == byMinutesID {
			foundByMinutes = true
			if scheduled.Type != "byminutes" || scheduled.NextNotificationAt.IsZero() {
				t.Fatalf("unexpected byminutes scheduled notification: %+v", scheduled)
			}
		}

		if scheduled.ID == dailyID {
			foundDaily = true
			if scheduled.Type != "daily" || scheduled.NextNotificationAt.IsZero() {
				t.Fatalf("unexpected daily scheduled notification: %+v", scheduled)
			}
		}
	}

	if !foundByMinutes || !foundDaily {
		t.Fatalf("expected both byminutes and daily notifications in schedule state")
	}
}

func TestJSONNotificationConfigStoreHandlesInvalidJSON(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "notification_config.json")
	if err := os.WriteFile(filePath, []byte("not-json"), 0o644); err != nil {
		t.Fatalf("failed to prepare invalid json file: %v", err)
	}

	store := NewJSONNotificationConfigStore(filePath)

	err := store.SetChannel(context.Background(), "guild-1", "channel-1")
	if err == nil {
		t.Fatal("expected error, got nil")
	}
}
